### ISSUE TITLE
Please consider renaming this repository

### ISSUE THREAD

**Issue by christian-schlichtherle** [DieTechniker/secon-tool#15]
This is only a suggestion with the following motivation:

Currently, this repository is named kks-encryption. This is a bit misleading because encryption is only one of four operations this library actually does, with the other being signing, verifying and decryption. Plus, this library also has additional features to use Java keystores for proving identity, looking up certificates or using an LDAP for looking up certificates and also general I/O tasks like fast copying of data.

Therefore, I would like to propose to rename this repository to "kks-tool" instead. This would also reflect the fact that you can use the fat-jar of this library as a command line tool.

**Comment by loetifuss** [comment]
There's been some discussion concerning the naming here at TK too. Some colleagues mentioned that the term "KKS" is fairly outdated and refers to file structures. See [KKS](https://www.gkv-datenaustausch.de/media/dokumente/standards_und_normen/technische_spezifikationen/Anlage_1_-_Krankenkassenkommunikationssystem.pdf)
This library is based on the specification in "Anlage 16 Security Schnittstelle (SECON)". So how about "secon-tool" or something similar? The term "KKS" is not mentioned at all in ["Anlage 16"](https://www.gkv-datenaustausch.de/media/dokumente/standards_und_normen/technische_spezifikationen/Anlage_16.pdf).

**Comment by loetifuss** [comment]
done, after internal discussion the repository has been renamed to "secon-tool" in accordance to the underlying SECON specification
