### ISSUE TITLE
Please create a first release

### ISSUE THREAD

**Issue by christian-schlichtherle** [DieTechniker/secon-tool#17]
... on Maven Central.

**Comment by loetifuss** [comment]
in progress: https://issues.sonatype.org/browse/OSSRH-60634
need to wait for final approval of using Apache License 2.0

**Comment by christian-schlichtherle** [comment]
You may need to update the groupID and artifactId in he Gradle build files before creating the release.

**Comment by reitzig** [comment]
We'd also take snapshot releases in the Github registry, if that's any easier. :grimacing:

**Comment by reitzig** [comment]
That was quick, thanks! :+1:

**Comment by loetifuss** [comment]
Just released version 1.0.0 on _oss.sonatype.org_. It should be available in a few hours on Maven Central:

> de.tk.opensource:secon-tool:1.0.0
