### ISSUE TITLE
Improve documentation over the command line tool params

### ISSUE THREAD

**Issue by rahadi** [DieTechniker/secon-tool#19]
Currenly there is no description about the parameters being passed to the command line tool. an example with some description would be much better.

**Comment by christian-schlichtherle** [comment]
but... it prints a usage message with a synopsis when you don't provide correct parameters.

**Comment by rahadi** [comment]
yes it does, but what I mean is to provide extra information over the params. for example: I don't know what to provide the value of  [-storetype <type>] ?

**Comment by christian-schlichtherle** [comment]
That could be any type of keystore supported by the Java Runtime Environment you are using, so it's not defined by the KKS tool.

For your reference: https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#KeyStore

If you don't bother, I recommend to use the `PKCS12` type.

**Comment by rahadi** [comment]
If you think there is no need for further description and explanation over the params, feel free to close the issue. thanks

**Comment by christian-schlichtherle** [comment]
As another reference, there is also the Java keytool: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html#keytool_option_certreq

The `-keystore`, `-storepass`, `-storetype`, `-alias` and `-keypass` parameters have exactly the same semantics as for the keytool.

**Comment by christian-schlichtherle** [comment]
This ticket can be closed. The command line options have been documented inline, now.
