### ISSUE TITLE
CertificateNotFoundException

### ISSUE THREAD

**Issue by RobertPrediger** [DieTechniker/secon-tool#39]
Hi,
when sending files to the insurance company, we get this error:
```
VERIFY: iaik.cms.CertificateNotFoundException: Certificate for verifying the signature not found!
```
At the moment we are stuck, because we don't have a glue, why this happens.
Kubus says, they do have our new 4k certificate.
When signing and encrypting the file, there is no error message.
In our opinion, the keystore is fine, we imported the root and our certificates. 
How can we test this or find this error?

Thanks in advance.

**Comment by christian-schlichtherle** [comment]
As discussed, this is an issue with the certificate data in the LDAP server, which somehow is out of sync. Therefore, I recommend to close this ticket.
