### ISSUE TITLE
Ist es ein Fehler wegen Signatur oder was für ein Problem haben wir?

### ISSUE THREAD

**Issue by NEO1976** [DieTechniker/secon-tool#54]
Sehr geehrte Damen und Herren, 
wir haben bis jetzt für Document Management System die Produktpalette von Axway verwendet. Zurzeit haben wir eine Umstellung von Axway PassPort, das verwaltet den gesamt LDAP System und unsere Beratern von Axway haben uns Secon Tool empfohlen. Wir haben die Einstellungen schon richtig gemacht und alles unter Axway B2Bi eingestellt und die Umstellung gemacht. Zurzeit bekommen wir von manchen Dokumenten (nicht von allen) die folgende Fehlermeldung:
<code>Exception in thread "main" de.tk.opensource.secon.SeconException: java.io.IOException: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat de.tk.openso urce.secon.SECON.lambda$6(SECON.java:268)XXat de.tk.opensource.secon.SECON.call(SECON.java:256)XXat de.tk.opensource.secon.SECON.copy(SECON.java:245)XXat de.tk.opensource.secon.Main.run(Main.java:126)XXat de.tk.opensource.secon.Main.main(Ma in.java:31)XCaused by: java.io.IOException: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat de.tk.opensource.secon.DefaultSubscriber$1.verifyIo(Def aultSubscriber.java:208)XXat de.tk.opensource.secon.SideEffect.lambda$0(SideEffect.java:50)XXat de.tk.opensource.secon.SideEffect.runAll(SideEffect.java:35)XXat de.tk.opensource.secon.DefaultSubscriber$1.close(DefaultSubscriber.java:199)XXa t de.tk.opensource.secon.SideEffect.lambda$0(SideEffect.java:44)XXat de.tk.opensource.secon.SideEffect.runAll(SideEffect.java:35)XXat de.tk.opensource.secon.Streams$1.close(Streams.java:41)XXat global.namespace.fun.io.api.Socket.accept(Sock et.java:111)XXat global.namespace.fun.io.spi.Copy.copy(Copy.java:91)XXat global.namespace.fun.io.bios.BIOS.copy(BIOS.java:537)XXat de.tk.opensource.secon.SECON.lambda$4(SECON.java:246)XXat de.tk.opensource.secon.SECON.lambda$6(SECON.java:26 2)XX... 4 moreXCaused by: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat org.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)XXat org.b ouncycastle.cms.SignerInformation.verify(Unknown Source)XXat de.tk.opensource.secon.DefaultSubscriber$1.verify(DefaultSubscriber.java:219)XXat de.tk.opensource.secon.DefaultSubscriber$1.verifyIo(DefaultSubscriber.java:204)XX... 15 moreX; MBC179 - Sonstige Fehler bei der Entschluesselung und oder Signature Pruefung, BN: 04373776 StdERR >Exception in thread "main" de.tk.opensource.secon.SeconException: java.io.IOException: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat de.tk.openso urce.secon.SECON.lambda$6(SECON.java:268)XXat de.tk.opensource.secon.SECON.call(SECON.java:256)XXat de.tk.opensource.secon.SECON.copy(SECON.java:245)XXat de.tk.opensource.secon.Main.run(Main.java:126)XXat de.tk.opensource.secon.Main.main(Ma in.java:31)XCaused by: java.io.IOException: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat de.tk.opensource.secon.DefaultSubscriber$1.verifyIo(Def aultSubscriber.java:208)XXat de.tk.opensource.secon.SideEffect.lambda$0(SideEffect.java:50)XXat de.tk.opensource.secon.SideEffect.runAll(SideEffect.java:35)XXat de.tk.opensource.secon.DefaultSubscriber$1.close(DefaultSubscriber.java:199)XXa t de.tk.opensource.secon.SideEffect.lambda$0(SideEffect.java:44)XXat de.tk.opensource.secon.SideEffect.runAll(SideEffect.java:35)XXat de.tk.opensource.secon.Streams$1.close(Streams.java:41)XXat global.namespace.fun.io.api.Socket.accept(Sock et.java:111)XXat global.namespace.fun.io.spi.Copy.copy(Copy.java:91)XXat global.namespace.fun.io.bios.BIOS.copy(BIOS.java:537)XXat de.tk.opensource.secon.SECON.lambda$4(SECON.java:246)XXat de.tk.opensource.secon.SECON.lambda$6(SECON.java:26 2)XX... 4 moreXCaused by: org.bouncycastle.cms.CMSException: The content-type attribute type MUST be present whenever signed attributes are present in signed-dataXXat org.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)XXat org.b ouncycastle.cms.SignerInformation.verify(Unknown Source)XXat de.tk.opensource.secon.DefaultSubscriber$1.verify(DefaultSubscriber.java:219)XXat de.tk.opensource.secon.DefaultSubscriber$1.verifyIo(DefaultSubscriber.java:204)XX... 15 moreX</code>

Obwohl ich Senior Java Entwickler bin, habe ich in meiner Arbeitsumgebung andere Rolle und deshalb habe ich leider keine IDEs . Deshalb konnte ich den Quellcode nicht richtig debuggen. Ich habe folgende Fragen:

1) Was müssen wir noch auf Axway Backend "Message Builder Component - MBC" System achten oder umprogrammieren?
2) Geht es hier um fehlende Signaturen?

Vielen Dank für Ihre Unterstützung im Voraus.

Mit freundlichen Grüßen

Hürol Türen

**Comment by loetifuss** [comment]
Hallo,

das secon-tool implementiert die Spezifikation für den Datenaustausch im Gesundheits- und Sozialwesen wie vom GKV definiert (siehe hier https://www.gkv-datenaustausch.de/media/dokumente/standards_und_normen/technische_spezifikationen/Anlage_16_-_Security_Schnittstelle.pdf)
Inwiefern secon-tool zu dem von Ihnen genannten Axway-Produkt passt kann ich nicht beurteilen, da ich Axway Passport und dessen Verwendung bei ihnen nicht kenne.

Die Fehlermeldung zeigt jedenfalls an, dass bei der Signaturprüfung ein nötiges Attribut "content-type" mit der OID 1.2.840.113549.1.9.3 in der Signatur fehlt, siehe auch https://oidref.com/1.2.840.113549.1.9.3.
